#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import math
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

import numpy as np


DEFAULT_EXCLUDED = {f"coif{i}" for i in range(10, 18)}


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def default_cpu_bin() -> Path:
    env_path = os.environ.get("CPU_WAVELET_CLI")
    if env_path:
        return Path(env_path)

    root = Path(__file__).resolve().parents[1]
    candidates = [
        root / "build" / "cpu_wavelet_cli.exe",
        root / "build" / "cpu_wavelet_cli",
        root / "build" / "Debug" / "cpu_wavelet_cli.exe",
        root / "build" / "Release" / "cpu_wavelet_cli.exe",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare CPU lifting outputs against PyWavelets for saved short signals."
    )
    parser.add_argument(
        "--signals",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "tests" / "data" / "signals_short.json",
        help="Signal dataset JSON generated by generate_signals.py.",
    )
    parser.add_argument(
        "--schemes-dir",
        type=Path,
        default=repo_root() / "tt-wavelet" / "ttnn-wavelet" / "lifting_schemes",
        help="Directory containing lifting scheme JSON files.",
    )
    parser.add_argument(
        "--cpu-bin",
        type=Path,
        default=default_cpu_bin(),
        help="Path to cpu_wavelet_cli executable.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "tests" / "results" / "accuracy.csv",
        help="Output CSV path.",
    )
    parser.add_argument(
        "--dtype",
        choices=["float", "double"],
        default="float",
        help="CPU transform dtype.",
    )
    parser.add_argument(
        "--include-excluded",
        action="store_true",
        help="Include numerically unstable coif10-coif17 schemes.",
    )
    parser.add_argument(
        "--wavelet",
        action="append",
        help="Restrict to one or more wavelet names. Can be passed multiple times.",
    )
    parser.add_argument(
        "--max-cases",
        type=int,
        default=0,
        help="Optional limit for quick local smoke runs. 0 means all cases.",
    )
    return parser.parse_args()


def load_pywt() -> Any:
    try:
        import pywt  # type: ignore[import-not-found]
    except ModuleNotFoundError as error:
        raise SystemExit(
            "PyWavelets is required for accuracy comparison. Install it in the active Python environment."
        ) from error
    return pywt


def signal_csv(values: list[float]) -> str:
    return ",".join(f"{float(value):.17g}" for value in values)


def run_cpu(cpu_bin: Path, scheme_path: Path, values: list[float], dtype: str) -> tuple[np.ndarray, np.ndarray]:
    completed = subprocess.run(
        [
            str(cpu_bin),
            "--scheme",
            str(scheme_path),
            "--signal",
            signal_csv(values),
            "--dtype",
            dtype,
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr.strip() or completed.stdout.strip())

    payload = json.loads(completed.stdout)
    return (
        np.asarray(payload["cA"], dtype=np.float64),
        np.asarray(payload["cD"], dtype=np.float64),
    )


def mse(lhs: np.ndarray, rhs: np.ndarray) -> float:
    if lhs.size == 0:
        return 0.0
    diff = lhs - rhs
    return float(np.mean(diff * diff))


def max_abs(lhs: np.ndarray, rhs: np.ndarray) -> float:
    if lhs.size == 0:
        return 0.0
    return float(np.max(np.abs(lhs - rhs)))


def iter_scheme_paths(schemes_dir: Path, selected: set[str] | None, include_excluded: bool) -> list[Path]:
    paths = sorted(path for path in schemes_dir.glob("*.json") if path.is_file())
    out: list[Path] = []
    for path in paths:
        name = path.stem
        if selected is not None and name not in selected:
            continue
        if not include_excluded and name in DEFAULT_EXCLUDED:
            continue
        out.append(path)
    return out


def classify(mse_a: float, mse_d: float) -> str:
    worst = max(mse_a, mse_d)
    if worst < 5e-6:
        return "green"
    if worst < 1e-2:
        return "yellow"
    return "red"


def main() -> int:
    args = parse_args()
    pywt = load_pywt()

    if not args.cpu_bin.exists():
        raise FileNotFoundError(
            f"CPU CLI not found: {args.cpu_bin}. Build cpu_wavelet_cli first or pass --cpu-bin."
        )
    if not args.signals.exists():
        raise FileNotFoundError(
            f"Signal dataset not found: {args.signals}. Run tools/generate_signals.py first."
        )

    dataset = json.loads(args.signals.read_text(encoding="utf-8"))
    signal_cases = list(dataset["cases"])
    selected = set(args.wavelet) if args.wavelet else None
    scheme_paths = iter_scheme_paths(args.schemes_dir, selected, args.include_excluded)

    rows: list[dict[str, Any]] = []
    total = 0
    failures = 0
    color_counts = {"green": 0, "yellow": 0, "red": 0}

    for scheme_path in scheme_paths:
        wavelet_name = scheme_path.stem
        try:
            wavelet = pywt.Wavelet(wavelet_name)
        except Exception as error:  # noqa: BLE001
            rows.append(
                {
                    "wavelet": wavelet_name,
                    "signal_kind": "",
                    "length": "",
                    "seed": "",
                    "status": "skip",
                    "class": "",
                    "error": f"no PyWavelets wavelet: {error}",
                    "mse_approx": math.nan,
                    "mse_detail": math.nan,
                    "max_abs_approx": math.nan,
                    "max_abs_detail": math.nan,
                }
            )
            continue

        for case in signal_cases:
            if args.max_cases and total >= args.max_cases:
                break

            values = [float(value) for value in case["values"]]
            base_row = {
                "wavelet": wavelet_name,
                "signal_kind": case["kind"],
                "length": int(case["length"]),
                "seed": "" if case["seed"] is None else int(case["seed"]),
            }

            try:
                cpu_a, cpu_d = run_cpu(args.cpu_bin, scheme_path, values, args.dtype)
                pywt_a, pywt_d = pywt.dwt(
                    np.asarray(values, dtype=np.float32),
                    wavelet=wavelet,
                    mode="symmetric",
                )
                pywt_a = np.asarray(pywt_a, dtype=np.float64)
                pywt_d = np.asarray(pywt_d, dtype=np.float64)

                if cpu_a.shape != pywt_a.shape or cpu_d.shape != pywt_d.shape:
                    raise RuntimeError(
                        f"length mismatch cpu={cpu_a.shape}/{cpu_d.shape} pywt={pywt_a.shape}/{pywt_d.shape}"
                    )

                mse_a = mse(pywt_a, cpu_a)
                mse_d = mse(pywt_d, cpu_d)
                row_class = classify(mse_a, mse_d)
                color_counts[row_class] += 1
                rows.append(
                    {
                        **base_row,
                        "status": "ok",
                        "class": row_class,
                        "error": "",
                        "mse_approx": mse_a,
                        "mse_detail": mse_d,
                        "max_abs_approx": max_abs(pywt_a, cpu_a),
                        "max_abs_detail": max_abs(pywt_d, cpu_d),
                    }
                )
            except Exception as error:  # noqa: BLE001
                failures += 1
                rows.append(
                    {
                        **base_row,
                        "status": "error",
                        "class": "red",
                        "error": str(error),
                        "mse_approx": math.nan,
                        "mse_detail": math.nan,
                        "max_abs_approx": math.nan,
                        "max_abs_detail": math.nan,
                    }
                )

            total += 1

        if args.max_cases and total >= args.max_cases:
            break

    args.output.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "wavelet",
        "signal_kind",
        "length",
        "seed",
        "status",
        "class",
        "error",
        "mse_approx",
        "mse_detail",
        "max_abs_approx",
        "max_abs_detail",
    ]
    with args.output.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"Schemes tested: {len(scheme_paths)}")
    print(f"Cases run: {total}")
    print(f"Failures: {failures}")
    print(
        "Classes: "
        f"green={color_counts['green']} yellow={color_counts['yellow']} red={color_counts['red']}"
    )
    print(f"CSV saved: {args.output}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
